In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
data_1d = np.array([1,2,3,4,5])

In [4]:
data_2d = np.array([[1,2,3],[4,5,6]])

In [5]:
print(data_1d.shape)

(5,)


In [6]:
print(data_2d.shape)

(2, 3)


In [7]:
reshaped_2d = data_2d.reshape(3,2)
print(reshaped_2d)

[[1 2]
 [3 4]
 [5 6]]


In [8]:
print(data_2d.ndim)

2


In [9]:
print(data_1d[3])

4


In [10]:
print(data_2d[1,2])

6


In [11]:
print(reshaped_2d[2,1])

6


In [12]:
print(data_1d[:3])

[1 2 3]


In [13]:
print(data_2d[:,1:])

[[2 3]
 [5 6]]


In [14]:
a = np.array([1,2,3])
b = np.array([4,5,6])


In [15]:
add = a+b
print(add)

[5 7 9]


In [16]:
sub = b-a
print(sub)

[3 3 3]


In [17]:
sub1 = a-b
print(sub1)

[-3 -3 -3]


In [18]:
print(sub)

[3 3 3]


In [19]:
mul = a*b
print(mul)

[ 4 10 18]


In [20]:
mul

array([ 4, 10, 18])

In [21]:
exp_a = np.exp(a)
exp_a

array([ 2.71828183,  7.3890561 , 20.08553692])

In [22]:
log_b = np.log(b)
log_b

array([1.38629436, 1.60943791, 1.79175947])

In [23]:
ab = np.array([1,2,3,4,5])
ba = 10

res = ab+ba
res

array([11, 12, 13, 14, 15])

In [24]:
t_sum = np.sum(b)
t_sum

np.int64(15)

In [26]:
c_sum = np.sum(data_1d,axis=0)
c_sum

np.int64(15)

In [29]:
b=np.array([[1,2,3],[4,5,6]])
c_sum=np.sum(b,axis=1)
c_sum

array([ 6, 15])

In [31]:
row_mean = np.mean(b,axis=0)
row_mean

array([2.5, 3.5, 4.5])